version: '3.7'

services:

  django:
    container_name: django_server
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ".:/app"
    ports:
      - 8000:8000
    depends_on:
      - react

  react:
    image: node
    container_name: react-web
    volumes: 
      - "./frontend:/app"
    command: cd app/frontend && npm run dev