# Generated by Django 3.1.6 on 2021-02-09 08:26

from decimal import Decimal
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Balance')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is online')),
                ('phone', models.CharField(max_length=12, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product title')),
                ('description', models.TextField(default='undefined', verbose_name='Product description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Product image')),
                ('price', models.IntegerField(default='free', verbose_name='Product price')),
                ('category', models.ForeignKey(default='Motor', on_delete=django.db.models.deletion.CASCADE, to='bazar.category', verbose_name='Category')),
                ('city', models.ForeignKey(default='Penza', on_delete=django.db.models.deletion.CASCADE, to='bazar.city', verbose_name='City')),
            ],
        ),
    ]
