# Generated by Django 3.1.6 on 2021-04-11 22:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='products',
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ManyToManyField(default=None, related_name='Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Publish date'),
        ),
    ]
