# Generated by Django 3.1.6 on 2021-08-22 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20210609_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='bazar.category', verbose_name='Категория родитель'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='bazar.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='bazar.city', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='unnamed.png', null=True, upload_to='product_images', verbose_name='Фото объявления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(default='Бесплатно', max_length=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Товар продан'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название объявления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='users', to='bazar.Post', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='В сети'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
