# Generated by Django 3.1.6 on 2021-02-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product title')),
                ('description', models.TextField(default='undefined', verbose_name='Product description')),
                ('image', models.ImageField(blank=True, height_field=250, null=True, upload_to='product_images', verbose_name='Product image', width_field=250)),
                ('price', models.IntegerField(default='free', verbose_name='Product price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.category', verbose_name='Category')),
            ],
        ),
    ]
